### ISSUE TITLE
Multiple Mailtrap accounts with one behat.yml

### ISSUE THREAD

**Issue by smijo149** [tyler43636/Behat-Mail-Extension#6]
Each dev needs their own mailtrap config. Is it possible to configure the Mailtrap API keys outside the behat.yml file? behat.yml is committed on github.

**Comment by tyler43636** [comment]
You can use BEHAT_PARAMS to set config settings in an environment variable. Just remember to remove the setting from the yaml file as it trumps the BEHAT_PARAMS settings. 

http://docs.behat.org/en/v3.0/user_guide/configuration.html
